// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh3G0urp1zE5P_eeOUoMdaTdM9tyFbe0U',
    appId: '1:529400016936:web:005854f19c2a13b5d3851d',
    messagingSenderId: '529400016936',
    projectId: 'gdgoc-com-app',
    authDomain: 'gdgoc-com-app.firebaseapp.com',
    storageBucket: 'gdgoc-com-app.firebasestorage.app',
    measurementId: 'G-2Y8KB83JP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxujh3a4OkNyd7qwf3NUhP0jcJXBhN9aM',
    appId: '1:529400016936:android:812f70350c023322d3851d',
    messagingSenderId: '529400016936',
    projectId: 'gdgoc-com-app',
    storageBucket: 'gdgoc-com-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDriVZMDB8qnKtMRfwHYWRbG-7X5CHSHMw',
    appId: '1:529400016936:ios:d06f298ced81a717d3851d',
    messagingSenderId: '529400016936',
    projectId: 'gdgoc-com-app',
    storageBucket: 'gdgoc-com-app.firebasestorage.app',
    iosBundleId: 'com.gdgoc2025.gdgoccom.gdgocCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDriVZMDB8qnKtMRfwHYWRbG-7X5CHSHMw',
    appId: '1:529400016936:ios:d06f298ced81a717d3851d',
    messagingSenderId: '529400016936',
    projectId: 'gdgoc-com-app',
    storageBucket: 'gdgoc-com-app.firebasestorage.app',
    iosBundleId: 'com.gdgoc2025.gdgoccom.gdgocCom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh3G0urp1zE5P_eeOUoMdaTdM9tyFbe0U',
    appId: '1:529400016936:web:25650de8a89f40a7d3851d',
    messagingSenderId: '529400016936',
    projectId: 'gdgoc-com-app',
    authDomain: 'gdgoc-com-app.firebaseapp.com',
    storageBucket: 'gdgoc-com-app.firebasestorage.app',
    measurementId: 'G-N4MMXDNC6M',
  );
}
